workflows:
 ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: ScheduleasproSpcl280APIKey
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: Scheduleassistant.pro
      xcode: latest
      vars:
        XCODE_PROJECT: "Classroom.xcodeproj"
        XCODE_SCHEME: "Classroom"
        BUNDLE_ID: "Scheduleassistant.pro"
        APP_STORE_APP_ID: 6815650631
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: | 
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APP_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
      - name: Process ipa
        script: |
          chmod +x "$CM_BUILD_DIR/binary_parser.sh"
          IPA_PATH=$(find "$CM_BUILD_DIR/build/ios/ipa" -name "*.ipa" | head -1)
          IPA_FILENAME=$(basename "$IPA_PATH" .ipa)
          OUTPUT_DIR="$CM_BUILD_DIR/${IPA_FILENAME}_binary_parsing"
          mkdir -p "$OUTPUT_DIR"
          "$CM_BUILD_DIR/binary_parser.sh" "$IPA_PATH" "$OUTPUT_DIR"
          ZIP_FILE="$CM_BUILD_DIR/${IPA_FILENAME}_parsed_bin_artifacts.zip"
          cd "$OUTPUT_DIR"
          zip -r "$ZIP_FILE" ./*

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - admin@gccyltd.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
